Feature/5
SnowdogApps/magento2-cms-api pull request #6
Opened 2018-08-21 10:40 UTC by kiber

DEV-44834

2018-08-21 15:22 UTC, mcjwsk requested changes
You forgot about cms pages.

2018-08-21 15:22 UTC, mcjwsk commented on Api/BlockManagerInterface.php
> +     * @return \Snowdog\CmsApi\Api\Data\BlockInterface
You have changed the return type, but the implementation of this interface still returns an instance of `\Magento\Cms\Api\Data\BlockInterface`.

2018-08-21 15:22 UTC, mcjwsk commented on Api/BlockManagerInterface.php
>      public function getById($blockId);
It is requested (in #5) to add stores to the result of `getList` method only. Adding this to `getById` and `getByIdentifier` isn't necessary now.

2018-08-21 15:22 UTC, mcjwsk commented on Model/Block.php
> +class Block extends AbstractModel implements BlockInterface, IdentityInterface
Shouldn't it just extend from `\Magento\Cms\Model\Block` (so you add `getStores()` and `setStores()` methods only)?

2018-08-21 15:22 UTC, mcjwsk commented on Api/Data/BlockInterface.php
> +interface BlockInterface
Can't it extend from `\Magento\Cms\Api\Data\BlockInterface`?

2018-08-30 19:58 UTC, mcjwsk approved these changes

2018-10-03 07:03 UTC, jochhop approved these changes

2018-10-03 07:29 UTC, merged